openapi: '3.0.2'
info:
  title: 采集平台配置中心
  version: '1.0'
  description: "这是用来配置consul的界面工具"
servers:
  - url: https://api.server.test/v1
paths:
  /user/login:
    post:
      tags:
        - user
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        default:
          description: successful operation
          content: { }
  /user/{username}:
    get:
      tags:
        - user
      summary: Get user by user name
      operationId: getUserByName
      parameters:
        - name: username
          in: path
          description: 'The name that needs to be fetched. Use user1 for testing. '
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid username supplied
          content: { }
        404:
          description: User not found
          content: { }
  /ftp/add:
    post:
      tags:
        - ftp
      summary: Create ftp
      description: 创建一个ftp
      operationId: AddFtp
      requestBody:
        description: 添加一个ftp
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Ftp'
        required: true
      responses:
        200:
          description: 返回信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resp'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          description: User Status
          format: int32
      xml:
        name: User
    Ftp:
      type: object
      properties:
        id:
          type: string
          description: ftp编号，如果设置则采用设置，否则会生成一个id
        trans_mode:
          type: string
          description: ftp模式
        province_name:
          type: string
          description: 省份
        cover_cities:
          type: string
          description: 城市
        file_type:
          type: string
          description: 文件类型
      xml:
        name: Ftp
    Resp:
      type: object
      properties:
        code:
          type: string
          default: "0000"
        msg:
          type: string
        data:
          type: object

